/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package event.obs.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import event.obs.model.Participant;
import event.obs.model.ParticipantModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Participant service. Represents a row in the &quot;OBS_Participant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ParticipantModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParticipantImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParticipantImpl
 * @generated
 */
@JSON(strict = true)
public class ParticipantModelImpl
	extends BaseModelImpl<Participant> implements ParticipantModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a participant model instance should use the <code>Participant</code> interface instead.
	 */
	public static final String TABLE_NAME = "OBS_Participant";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"idParticipant", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"idUser", Types.BIGINT}, {"entite", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idParticipant", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("idUser", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entite", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OBS_Participant (uuid_ VARCHAR(75) null,idParticipant LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,idUser LONG,entite VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table OBS_Participant";

	public static final String ORDER_BY_JPQL =
		" ORDER BY participant.idParticipant ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OBS_Participant.idParticipant ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDPARTICIPANT_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ParticipantModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idParticipant;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdParticipant(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idParticipant;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Participant.class;
	}

	@Override
	public String getModelClassName() {
		return Participant.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Participant, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Participant, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Participant, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Participant)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Participant, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Participant, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Participant)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Participant, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Participant, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Participant, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Participant, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Participant, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Participant, Object>>();
		Map<String, BiConsumer<Participant, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Participant, ?>>();

		attributeGetterFunctions.put("uuid", Participant::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Participant, String>)Participant::setUuid);
		attributeGetterFunctions.put(
			"idParticipant", Participant::getIdParticipant);
		attributeSetterBiConsumers.put(
			"idParticipant",
			(BiConsumer<Participant, Long>)Participant::setIdParticipant);
		attributeGetterFunctions.put("groupId", Participant::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Participant, Long>)Participant::setGroupId);
		attributeGetterFunctions.put("companyId", Participant::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Participant, Long>)Participant::setCompanyId);
		attributeGetterFunctions.put("createDate", Participant::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Participant, Date>)Participant::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Participant::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Participant, Date>)Participant::setModifiedDate);
		attributeGetterFunctions.put("idUser", Participant::getIdUser);
		attributeSetterBiConsumers.put(
			"idUser", (BiConsumer<Participant, Long>)Participant::setIdUser);
		attributeGetterFunctions.put("entite", Participant::getEntite);
		attributeSetterBiConsumers.put(
			"entite", (BiConsumer<Participant, String>)Participant::setEntite);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getIdParticipant() {
		return _idParticipant;
	}

	@Override
	public void setIdParticipant(long idParticipant) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idParticipant = idParticipant;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getIdUser() {
		return _idUser;
	}

	@Override
	public void setIdUser(long idUser) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idUser = idUser;
	}

	@JSON
	@Override
	public String getEntite() {
		if (_entite == null) {
			return "";
		}
		else {
			return _entite;
		}
	}

	@Override
	public void setEntite(String entite) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entite = entite;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Participant.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Participant.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Participant toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Participant>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ParticipantImpl participantImpl = new ParticipantImpl();

		participantImpl.setUuid(getUuid());
		participantImpl.setIdParticipant(getIdParticipant());
		participantImpl.setGroupId(getGroupId());
		participantImpl.setCompanyId(getCompanyId());
		participantImpl.setCreateDate(getCreateDate());
		participantImpl.setModifiedDate(getModifiedDate());
		participantImpl.setIdUser(getIdUser());
		participantImpl.setEntite(getEntite());

		participantImpl.resetOriginalValues();

		return participantImpl;
	}

	@Override
	public Participant cloneWithOriginalValues() {
		ParticipantImpl participantImpl = new ParticipantImpl();

		participantImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		participantImpl.setIdParticipant(
			this.<Long>getColumnOriginalValue("idParticipant"));
		participantImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		participantImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		participantImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		participantImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		participantImpl.setIdUser(this.<Long>getColumnOriginalValue("idUser"));
		participantImpl.setEntite(
			this.<String>getColumnOriginalValue("entite"));

		return participantImpl;
	}

	@Override
	public int compareTo(Participant participant) {
		long primaryKey = participant.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Participant)) {
			return false;
		}

		Participant participant = (Participant)object;

		long primaryKey = participant.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Participant> toCacheModel() {
		ParticipantCacheModel participantCacheModel =
			new ParticipantCacheModel();

		participantCacheModel.uuid = getUuid();

		String uuid = participantCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			participantCacheModel.uuid = null;
		}

		participantCacheModel.idParticipant = getIdParticipant();

		participantCacheModel.groupId = getGroupId();

		participantCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			participantCacheModel.createDate = createDate.getTime();
		}
		else {
			participantCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			participantCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			participantCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		participantCacheModel.idUser = getIdUser();

		participantCacheModel.entite = getEntite();

		String entite = participantCacheModel.entite;

		if ((entite != null) && (entite.length() == 0)) {
			participantCacheModel.entite = null;
		}

		return participantCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Participant, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Participant, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Participant, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Participant)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Participant>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Participant.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _idParticipant;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _idUser;
	private String _entite;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Participant, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Participant)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("idParticipant", _idParticipant);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("idUser", _idUser);
		_columnOriginalValues.put("entite", _entite);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("idParticipant", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("idUser", 64L);

		columnBitmasks.put("entite", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Participant _escapedModel;

}