/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package event.obs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Participant service. Represents a row in the &quot;OBS_Participant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>event.obs.model.impl.ParticipantModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>event.obs.model.impl.ParticipantImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Participant
 * @generated
 */
@ProviderType
public interface ParticipantModel
	extends BaseModel<Participant>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a participant model instance should use the {@link Participant} interface instead.
	 */

	/**
	 * Returns the primary key of this participant.
	 *
	 * @return the primary key of this participant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this participant.
	 *
	 * @param primaryKey the primary key of this participant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this participant.
	 *
	 * @return the uuid of this participant
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this participant.
	 *
	 * @param uuid the uuid of this participant
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id participant of this participant.
	 *
	 * @return the id participant of this participant
	 */
	public long getIdParticipant();

	/**
	 * Sets the id participant of this participant.
	 *
	 * @param idParticipant the id participant of this participant
	 */
	public void setIdParticipant(long idParticipant);

	/**
	 * Returns the group ID of this participant.
	 *
	 * @return the group ID of this participant
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this participant.
	 *
	 * @param groupId the group ID of this participant
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this participant.
	 *
	 * @return the company ID of this participant
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this participant.
	 *
	 * @param companyId the company ID of this participant
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this participant.
	 *
	 * @return the create date of this participant
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this participant.
	 *
	 * @param createDate the create date of this participant
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this participant.
	 *
	 * @return the modified date of this participant
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this participant.
	 *
	 * @param modifiedDate the modified date of this participant
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the id user of this participant.
	 *
	 * @return the id user of this participant
	 */
	public long getIdUser();

	/**
	 * Sets the id user of this participant.
	 *
	 * @param idUser the id user of this participant
	 */
	public void setIdUser(long idUser);

	/**
	 * Returns the entite of this participant.
	 *
	 * @return the entite of this participant
	 */
	@AutoEscape
	public String getEntite();

	/**
	 * Sets the entite of this participant.
	 *
	 * @param entite the entite of this participant
	 */
	public void setEntite(String entite);

	@Override
	public Participant cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}